collegedata<-read.csv("C:\\projects\\Engg_College_Data.csv",header=TRUE)
head(collegedata)
tail(collegedata)
str(collegedata)
ncol(collegedata)
nrow(collegedata)
colSums(is.na(collegedata))
colnames(collegedata[sapply(collegedata,is.numeric)])
colnames(collegedata[!sapply(collegedata,is.numeric)])
unique(collegedata$Teaching)
unique(collegedata$Fees)
unique(collegedata$Placements)
unique(collegedata$Internship)
unique(collegedata$Infrastructure)

require(ggplot2)
plot(Teaching~Fees,data=collegedata)
plot(Teaching~Placements,data=collegedata)
plot(Teaching~Internship,data=collegedata)
plot(Teaching~Infrastructure,data=collegedata)
plot(Fees~Placements,data=collegedata)
plot(Fees~Internship,data=collegedata)
plot(Fees~Infrastructure,data=collegedata)
plot(Placements~Internship,data=collegedata)
plot(Placements~Infrastructure,data=collegedata)
plot(Internship~Infrastructure,data=collegedata)
d.chebyshev <- dist(x=collegedata[,c("Teaching","Fees","Placements","Internship","Infrastructure")], method ="maximum")
d.chebyshev
res.hclust <- hclust(d.chebyshev, method = "complete")
plot(res.hclust, labels = as.character(collegedata[,2]))
cluster.height<-res.hclust$height
cluster.height<- sort(cluster.height, decreasing = TRUE)
plot(cluster.height)
lines(cluster.height,lty=2,lwd=2)

plot(res.hclust, labels = as.character(collegedata[,2]))
rect.hclust(res.hclust, k=3, border="red")
groups<-cutree(res.hclust, k=3)
collegedata<-cbind(collegedata,groups)
group1<- subset(collegedata, groups==1)
group2<- subset(collegedata, groups==2)
group3<- subset(collegedata, groups==3)
group1
group2
group3
